---
- name: Remove cache dir manually.
  file: state=absent path={{symfony_dir}}/app/cache/{{env}}
  when: enable_cache_warmup == True
  tags:
    - cache

- name: Warmup sf cache.
  shell: cd {{symfony_dir}} && export SYMFONY_ENV={{env}}; {{php_path}} {{symfony_console}} {{cache_command}} {{console_opts}}
  when: enable_cache_warmup == True
  tags:
    - cache