---
# tasks file for symfony2
- name: Pull sources from the repository.
  git: repo={{repo}} dest={{symfony_dir}} version={{branch}} accept_hostkey=yes

- name: Read composer.json
  shell: cat {{symfony_dir}}/composer.json
  register: composer_content

- include: "{{post_folder_creation_tasks}}"

- include: 00-config.yml

- include: 10-composer.yml

- include: "{{pre_cache_warmup_tasks}}"

- include: 20-cache.yml

- include: 30-assets.yml

- include: 40-migrations.yml

- include: 50-permissions.yml